server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    username: root
    password: ola24oluwa
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Book Store Application
  h2:
    console:
      enabled:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled:  true
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher